### ISSUE TITLE
The MyButton.onlclick does not work

### ISSUE THREAD

**Issue by RPIERIS** [mdn/beginner-html-site-scripted#13]
Hi 

My assumption is that when I press the Change user button it will rerun the setUserName function. However the no promt come up to do so. I have used a getelementID to carry this out and it works. However in this case it keeps repeating every single time I reload the page. 

I am completely new to Javascript but appreciate any feedback you can provide.

**Comment by chrisdavidmills** [comment]
Hi there @RPIERIS !

Some ideas to help you out:

1. Our version of the code is running live at https://mdn.github.io/beginner-html-site-scripted/. This will show you the expected behavior. Basically, the image should change when you click it, and you should be prompted for a name when you first load the page, and when you click the button. It should remember your name whe you reload it.

2. Also check out our version of the code, at https://github.com/mdn/beginner-html-site-scripted/blob/gh-pages/scripts/main.js. Compare it to your code and see if you can work out where the differences lie.

3. If you are still stuck, send me a link to your code, and I'll have a look and see if I can work out what the problem is.

**Comment by SylvieCanongia** [comment]
Hi,

**Comment by SylvieCanongia** [comment]
Hi,
Same for me. the myButton.onclick does not work.

**Comment by LaLonchera956** [comment]
My image switcher is not working, can it be the image file name? or did i not write my code correctly?

let myImage = document.querySelector('img');

myImage.onclick = function() {
    let mySrc = myImage.getAttribute('src');
    if(mySrc === 'images/firefox-icon.png') {
        myImage.setAttribute('src',images/firefox2.png');
    } else {
        myImage.setAttribute('src','images/firefox-icon.png');
    }
}

**Comment by chrisdavidmills** [comment]
Have at look at our working source code (https://github.com/mdn/beginner-html-site-scripted/blob/gh-pages/scripts/main.js#L3) and see if you can find any differences. 

Also try copy our exact code over the top of yours, and seeing if it works then. If not, then the problem might be somewhere else.

**Comment by newan1352** [comment]
the javascript console gives this, "null is not an object". The code doesn't work because I literally copied it from here and it still gave me the same error.

**Comment by RPIERIS** [comment]
@chrisdavidmills apologies for taking so long to get back. I followed the instructions on MDN and it worked. I did pick up some syntax errors from looking at the console. Maybe this could be incorporated to the sections? 

I am following the front end course on MDN and using discourse to ask and answer questions and it is superb. BTW, the move to Github is excellent. I heard the JS Party Podcast "Who let the Docs out" and I think the way MDN is going is perfect. I hope I can help out in a year or two when I have some projects under my belt as a front end.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills apologies for taking so long to get back. I followed the instructions on MDN and it worked. I did pick up some syntax errors from looking at the console. Maybe this could be incorporated to the sections?

Yeah, maybe that would be wise. What errors are you getting in the console, and are those errors present in our final version?

> I am following the front end course on MDN and using discourse to ask and answer questions and it is superb. BTW, the move to Github is excellent. I heard the JS Party Podcast "Who let the Docs out" and I think the way MDN is going is perfect. I hope I can help out in a year or two when I have some projects under my belt as a front end.

I'm glad you like it, thanks for the comments! I've also noticed you helping out on the forums a bit; I really appreciate that too, as I've had very little time to do that recently.

**Comment by RPIERIS** [comment]
I was getting errors on mistyping prompt i.e. spelt it promt so got an undefined variable error I believe. There was something else which was also incorrectly spelled which the console soon showed up. 

I am learning loads from the forums. Also using it as a space to test my own knowledge. I havent finished the JS part yet as I decided that I needed to learn the HTML and CSS first. I came across this [Developer Roadmap](https://roadmap.sh/), again after listening to a JS party podcast ["Roadmaps to becoming a web developer in 2021"](https://changelog.com/jsparty/159) where the importance of HTML and CSS was highlighted. I think this is right. Need to know the basics first and then I can build up to the more complicated work. 

Let me know if I can help you and MDN in some small way. I would like to build up my Github profile as well.

**Comment by chrisdavidmills** [comment]
> I was getting errors on mistyping prompt i.e. spelt it promt so got an undefined variable error I believe. There was something else which was also incorrectly spelled which the console soon showed up.

Right, so you are kind of talking about something along the lines of "common errors and what they mean". Yeah, that sounds useful.

 
> I am learning loads from the forums. Also using it as a space to test my own knowledge. I havent finished the JS part yet as I decided that I needed to learn the HTML and CSS first. I came across this [Developer Roadmap](https://roadmap.sh/), again after listening to a JS party podcast ["Roadmaps to becoming a web developer in 2021"](https://changelog.com/jsparty/159) where the importance of HTML and CSS was highlighted. I think this is right. Need to know the basics first and then I can build up to the more complicated work.

Makes a lot of sense!
 
> Let me know if I can help you and MDN in some small way. I would like to build up my Github profile as well.

Well, we have loads of content issues that need fixing: https://github.com/mdn/content/issues. Just in and fixing a few of those would be a great help.

Maybe you could start with the addition we discussed above, as a test?

**Comment by RPIERIS** [comment]
> Maybe you could start with the addition we discussed above, as a test?

OK, let me have a look this weekend. I have never done this before so will look at https://github.com/mdn/content/blob/main/README.md. 

Thanks and I m looking forward to it

**Comment by schalkneethling** [comment]
Hey everyone, I hope you have been able to figure this one out. If not, please reach out to the community on our [learn forum](https://discourse.mozilla.org/c/mdn/learn/250).
