### ISSUE TITLE
myImage === null 

### ISSUE THREAD

**Issue by mblitstein** [mdn/beginner-html-site-scripted#4]
I got error messages indicating that myImage wasn't being set to the name of the image.

This was confirmed by an error trap (if(myImage === null ) {alert(myImage is null) .

I finally copied the GitHub version which replicate the previous bad behavior.
The errant code appears to be:
     var myImage = document.querySelector('img');

Has anyone else had this experience, or more importantly a fix?

Thanks

**Comment by chrisdavidmills** [comment]
Hi there,

I've tried out the GitHub version of the example (https://mdn.github.io/beginner-html-site-scripted/), and it seems to work fine for me. No errors or anything.

What browser are you trying to run the example in?

**Comment by mblitstein** [comment]
I tried it in Firefox, Chrome, and Edge. 

I started in Codepen. I'm beginning to think the problem may be in the pathnames. 

Thanks

**Comment by chrisdavidmills** [comment]
Ah yes - it uses relative paths, which would break if you put it in codepen. If you tried absolute paths, it would probably work.

**Comment by chrisdavidmills** [comment]
@ovirchenko Excellent; glad you got it worked out.
