### ISSUE TITLE
The thought about the designing 

### ISSUE THREAD

**Issue by ZijunXia** [mdn/beginner-html-site-scripted#7]
Well, firstly this is a pretty cool website, and the user can type the name before enter the website. I think the blue parts on the left and right can change to some information or features of Mozilla to show to the users. Also for the user name, the user can type anything and even any number or symbol, so if that can be changed should be better.

**Comment by chrisdavidmills** [comment]
I appreciate your ideas — these would certainly be handled better in a real site. But the design and code has deliberately been kept really simple here, so beginners do not get confused.
